<?php require "templates/Posts/header.php" ?>
<div class="container">
    <nav class="site-header  py-1">
        <div class="container d-flex  flex-md-row justify-content-end">
            <a class="py-2 mx-2 d-none d-md-inline-block"  href="/">На главную</a>
            <a class="py-2 mx-2 d-none d-md-inline-block" href="/posts">Посты</a>
        </div>
    </nav>
</div>

<div class="container">
    <?php foreach ($posts as $post):?>
    <div class="col-md-12">
        <h1><?= $post['name'] ?></h1>
        <p><?= $post['post'] ?></p>
        <div>
            <span class="badge">Posted 2012-08-02 20:47:04</span><div class="pull-right"><span class="label label-default">alice</span> <span class="label label-primary">story</span> <span class="label label-success">blog</span> <span class="label label-info">personal</span> <span class="label label-warning">Warning</span>
                <span class="label label-danger">Danger</span></div>
        </div>
    </div>

</div>

<form action="/posts/<?= $post['id'] ?>" method="POST">
    <input type="hidden" name="_METHOD" value="DELETE">
    <tr>
        <td>
             <input type="submit" value="Delete">
        </td>
    </tr>
</form>
<?php endforeach;?>